# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_album_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='album_id',
            field=models.IntegerField(default=0),
        ),
    ]
