# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180327_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.SmallIntegerField(default=0),
        ),
    ]
